spring:
  application:
    name: discovery-server #name should be equal to bootstrap's one
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/, http://localhost:8801/eureka/, http://localhost:8802/eureka/
  instance:
    prefer-ip-address: true # if you don't have own your DNS servers, perfer-ip-address is useful.
    instance-id: ${spring.application.name}-${spring.profiles.active}    
---
spring:
  profiles: peer1
server:
  port: 8800  
eureka:
  instance:
    metadata-map:
      zone: zone1
---
spring:
  profiles: peer2
server:
  port: 8801
eureka:
  instance:
    metadata-map:
      zone: zone2
---
spring:
  profiles: peer3  
server:
  port: 8802
eureka:
  instance:
    metadata-map:
      zone: zone3